version: "3"
services:
  web:
    image: nginx
    volumes:
      - ./code_1/:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "1234:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - "./code_1:/var/www"
    

  db:
    image: mariadb
    restart: always
    volumes:
      - ./code_1/database/dump.sql:/docker-entrypoint-initdb.d/sl_dump_file.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080